### PR TITLE
Fixes #318: versions:display-dependency-updates goal need to have exc…

### LINKED ISSUE #318: versions:display-dependency-updates goal need to have excludes and includes property
At present, if the following command is executed:
**mvn versions:display-dependency-updates**
```   <plugin>		
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>versions-maven-plugin</artifactId>
    <inherited>false</inherited>
    <configuration>
    <allowSnapshots>false</allowSnapshots>
    <outputFile>build/outdated-dependencies.txt</outputFile>
    <rulesUri>file:///C:rules.xml</rulesUri>
    <processDependencyManagement>false</processDependencyManagement> 
    <processPluginDependencies>false</processPluginDependencies>  
    </configuration>
    </plugin>
```
**The plugin currently scans for latest updates for all the dependencies listed in the pom file.**
In certain cases, we might need to scan the updates to a limited dependency or a particular classifier or scope.
The display-dependency-updates doesn't currently allow this to be done.
But, other goals like versions:use-latest-versions allows me to have the excludes and includes property in them.

### PR DESCRIPTION
**Pull request by HonoluluHenk**
…ludes and includes property

### CODE REVIEW

**Comment by HonoluluHenk** [comment]
I'd be happy to implement some tests if the implemented solution is viable

**Comment by aegliv** [comment]
I would love to see this PR merged. What is still missing?

**Comment by tfactor2** [comment]
No progress so far? For us it would be also very useful - we have a set of internal libraries and would like to keep the teams up-to-date with the newest library versions but don't want to check version updates for a full framework like Spring Boot.

**Comment by HonoluluHenk** [comment]
@stephenc care to comment or close as won't fix?

**Comment by stephenc** [comment]
I think others have been maintaining this plugin for a while now. Tbh my focus is not in a place where I can give this the care it needs. Try the last person to cut a release

**Comment by HonoluluHenk** [comment]
@mfriedenhagen care to comment or close as won't fix?

**Comment by tfactor2** [comment]
Still extremely relevant.
I saw the last commit from @mfriedenhagen - probably you can clarify the situation and make a decision about the issue?

Thx in advance.

**Comment by HonoluluHenk** [comment]
bump

**Comment by stefanseifert** [comment]
i can support this PR and help getting it merged and released.

some open issues/questions/remarks:
* this issue does *not* implement what the title and #318 suggests (=adding includes/excludes to `display-dependency-updates` properties as in `use-latest-versions`). instead, it adds a possibility to filter for scopes in dependency and dependencyManagement section. this is also useful, but a different issue and PR should be created.
* this PR has merge conflicts - can you rebase or merge it with current master?
* we also need an integration test for the new behavior

**Comment by fmdaboville** [comment]
@HonoluluHenk any news about the merge for this feature ?

**Comment by HonoluluHenk** [comment]
I just started a new PR addressing all of the issues mentioned by stefanseifert...

**Comment by HonoluluHenk** [comment]
closed because it is deprecated, 

@stefanseifert Could you instead review PR #602 ?

**Pull request closed without merging**
