### PR TITLE
'groupId' not always pulling from parent pom

### PR DESCRIPTION
**Pull request by tomerc**

### CODE REVIEW

**Comment by khmarbaise** [comment]
I assume that should fix issue #5? A reference to the issue in the log message would be furthermore a test would be very good...

**Comment by tomerc** [comment]
Added testcase

**Comment by khmarbaise** [comment]
Can you please squash your commits...

**Comment by tomerc** [comment]
Done

**Comment by khmarbaise** [comment]
Ok. Integrated. Thanks.

**Pull request closed without merging**
