### PR TITLE
Add missing space in exception message

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
May I ask for review, please?

**Comment by pzygielo** [comment]
@mfriedenhagen @hboutemy @stefanseifert - as you managed to commit to this repository _after_ this PR was opened - could you please review it?

**Comment by stefanseifert** [comment]
i've no commit rights, but it lgtm

**Comment by pzygielo** [comment]
@stefanseifert - thanks for checking

**Pull request closed without merging**
