### PR TITLE
Switch Maven Wrapper to 4.0.0-alpha-2

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Wrapper config is overrided by GitHub actions ...

Maybe we should add 4.x to GitHub action if we want to verify with 4 - but I would like try with only with one jdk ...

**Comment by slachiewicz** [comment]
Yes, but other developers can use mine locally

**Comment by slawekjaranowski** [comment]
@slachiewicz did you test with mvn 4 ...
I have:

```
[INFO] --- maven-enforcer-plugin:3.1.0:enforce (mojo-enforcer-rules) @ versions-maven-plugin ---
[ERROR] Rule 2: org.apache.maven.plugins.enforcer.RequirePluginVersions failed with message:
Some plugins are missing valid versions or depend on Maven 4.0.0-alpha-2 defaults: (LATEST RELEASE SNAPSHOT are not allowed)
org.apache.maven.plugins:maven-plugin-plugin.   The version currently in use is 3.6.4 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-site-plugin.     The version currently in use is 3.12.1 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-javadoc-plugin.  The version currently in use is 3.4.1 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-assembly-plugin.         The version currently in use is 3.4.2 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-resources-plugin.        The version currently in use is 3.3.0 via super POM or default lifecycle bindings
org.codehaus.mojo:mrm-maven-plugin.     The version currently in use is 1.4.1 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-compiler-plugin.         The version currently in use is 3.10.1 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-surefire-plugin.         The version currently in use is 3.0.0-M7 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-jar-plugin.      The version currently in use is 3.3.0 via super POM or default lifecycle bindings
org.codehaus.mojo:animal-sniffer-maven-plugin.  The version currently in use is 1.22 via super POM or default lifecycle bindings
org.codehaus.modello:modello-maven-plugin.      The version currently in use is 2.0.0 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-clean-plugin.    The version currently in use is 3.2.0 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-wrapper-plugin.  The version currently in use is 3.1.0 via default lifecycle bindings
org.apache.maven.plugins:maven-checkstyle-plugin.       The version currently in use is 3.2.0 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-install-plugin.  The version currently in use is 3.0.1 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-invoker-plugin.  The version currently in use is 3.3.0 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-deploy-plugin.   The version currently in use is 2.8.2 via super POM or default lifecycle bindings
org.apache.maven.plugins:maven-enforcer-plugin.         The version currently in use is 3.1.0 via super POM or default lifecycle bindings
Best Practice is to always define plugin versions!

```

**Comment by slachiewicz** [comment]
i would say yes, but looks like it fails on clean env setup even on my side. 

not clear what can be reason because if I set maven-plugin-version to 3.7.0 i'm getting same result. Only adding entry to pom.xml makes this error disappear.
Lets check this on other project - I reverted this change.

**Pull request merged**
