### PR TITLE
fix #25 use raw model for dependencyManagement

### LINKED ISSUE #25: Version updates ignore import scoped BOM dependencies
Version 2.2

As per http://stackoverflow.com/questions/7609876/how-to-make-maven-versionsuse-latest-versions-step-up-import-scoped-entry-in-de

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>se.company.maven</groupId>
            <artifactId>maven-third-party-dependencies</artifactId>
            <version>0.0.1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```
When we run mvn versions:use-latest-versions all our dependencies (and other entries in dependencyManagement) get stepped up except this one.

### PR DESCRIPTION
**Pull request by tavin**
this is a fix for https://github.com/mojohaus/versions-maven-plugin/issues/25

### CODE REVIEW

**Comment by khmarbaise** [comment]
Can you please squash your commits into a single one...

**Comment by tavin** [comment]
done

**Comment by khmarbaise** [comment]
Cool let the force be with the CI ...

**Comment by khmarbaise** [comment]
Ok The force is with you ;-)

**Comment by tavin** [comment]
cheers

**Pull request merged**
