### PR TITLE
#499 - Let update-parent support -DallowMajorUpdates and alike

### PR DESCRIPTION
**Pull request by askoog**
Implement support for `allowMajorUpdates`, `allowMinorUpdates` and `allowIncrementalUpdates` in update-parent

### CODE REVIEW

**Review by stefanseifert — CHANGES_REQUESTED** [review]
thanks for the PR - can you come up with integration tests as well for the new functionality?
please also rebase/merge with current develop branch to resolve the conflicts.

**Comment by slawekjaranowski** [comment]
@askoog thanks for refresh PR.

as @stefanseifert said, IT test will be appreciated
We should be sure with next changes that feature still works.

**Comment by ajarmoniuk** [comment]
@askoog Hi there, do you still want to finish this PR? If you want, I could take it over and finish what's left to do. Please reach out.

**Comment by askoog** [comment]
@ajarmoniuk Please feel free if you want to continue with this PR. I tried to fix errors and also added some tests, but when I rebased on master I see that you have made quite a few changes in the latest version and some of the methods I used have been removed :/
Probably you have more insight in how to implement this feature.

**Comment by ajarmoniuk** [comment]
Actually we'd like to give this *allow...Updates* system a slight overhaul, at least in its inner workings, since those options are not mutually independent and it's much better to represent them as e.g. an enum, at least internally. And, obviously, furnishing this mojo with this feature is coming :)

**Comment by askoog** [comment]
I see. Yes that sounds like a good idea. I guess it will be easier to implement the functionality in other mojos as well then.

The allowXxxUpdates is a great addition to this plugin and we use it very frequently. We have several hundred maven projects that we continuously keep up to date using this plugin and internally we have different major versions for our development platform projects based on java version, spring version etc. Upgrading to a different major is often a bigger task than just upgrading patch versions and therefore it is great to be able to perform automatic updates for just pathches/minors and not majors.

Anyhow, I will leave this PR to you, if you want to close it, go ahead. Feel free to reach out if there is anything I can help with

**Comment by ajarmoniuk** [comment]
Working on it. I'll wait till #733 is merged since I'd like to use the `BoundedArtifactVersions` there, just like in `UpdateLatestReleasesMojo`. 

Incrementing a segment to obtain the upper bound brings caveats with itself -- we may indadvertedly update to a beta or a snapshot version from the next major release because these lie before the .0 versions. Which my PR #733 fixes.

**Comment by slawekjaranowski** [comment]
@askoog thanks for your effort , I assume that now it is resolved by #737

**Pull request closed without merging**
