### PR TITLE
Fix #202 - use-reactor update parents

### LINKED ISSUE #202: -DprocessParent=true is ignored by user-reactor mojo
`processParent` parameter is ignored by user-reactor mojo.

The failing use case is:

1. Hierarchical project structure: A <- B <- C (where A and B are `<packaging>pom</packaging>` and C is `<packaging>jar</packaging>`
1. Parent relationship is on releases (C parent is the latest release of B, and B parent is the latest release of A)
1. Run `mvn versions:use-reactor -DprocessParent=true -DexcludeReactor=false -DallowSnapshots=true` on A (the grandparent).
1. Expected: C parent is updated to point to current version of B in the reactor, same of B.
1. What I get: parents are not updated at all.

### PR DESCRIPTION
**Pull request by amuniz**
See #202 for additional information.

### CODE REVIEW

**Comment by stephenc** [comment]
Could you add some integration tests?

**Comment by stephenc** [comment]
See https://github.com/mojohaus/versions-maven-plugin/tree/master/src/it for example integration tests

**Comment by amuniz** [comment]
Ok, will do. Thanks!

**Comment by amuniz** [comment]
@stephenc Tests added.

**Comment by amuniz** [comment]
Build is failing only on JDK7, but the failure seems unrelated to this change:

```
$ mvn --show-version --errors --batch-mode -Prun-its clean verify
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-7-oracle/bin/java
```

It is ok on JDK8.

**Pull request merged**
