### PR TITLE
New feature (#477): connection, developerConnection, url arguments for set-scm-tag

### PR DESCRIPTION
**Pull request by ajarmoniuk**
Adding the requested new features and modifying the first it for the feature.

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
`newTag` parameter is still required, we should require one of allowed parameters

**Comment by ajarmoniuk** [comment]
> `newTag` parameter is still required, we should require one of allowed parameters

Done.

**Comment by ajarmoniuk** [comment]
Please don't merge in yet.

**Comment by ajarmoniuk** [comment]
I have reworked the PR. 

It now lets the user define tags even if they weren't present before or the `scm` element was not present at all.

**Comment by ajarmoniuk** [comment]
Reverted to the old version of the PR: this version retains the original structure of POM. 

Corrected one found issue: newTag would always be applied regardless of being defined or not.

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
