### PR TITLE
#758: Implementing the first stage of module split

### PR DESCRIPTION
**Pull request by ajarmoniuk**

### CODE REVIEW

**Comment by ajarmoniuk** [comment]
I think we need some kind of a commit freeze in order to commit this -- too many changes.

**Comment by slawekjaranowski** [comment]
I have worked a little on site output.

Please check by:
```
mvn site site:stage
```

and investigate output in `target/staging/versions`

**Comment by ajarmoniuk** [comment]
> I have worked a little on site output.
> 
> Please check by:
> 
> ```
> mvn site site:stage
> ```
> 
> and investigate output in `target/staging/versions`

Maven site won't build anymore.

**Comment by slawekjaranowski** [comment]
> By the way, why did you remove the XSD schemas of the reports from the XSD section? I can re-add those unless you explicitly wanted those removed...

I moved it to place where is generated ... for old versions of XSD we will need place a copy in root site to preserver old path.
We will change repo name ... 😄

**Comment by slawekjaranowski** [comment]
> Looks like maven site requires the artifacts to be present in the local repo. So we need to do install -P run-its instead of verify in maven-verify.yml?

I see - we use under site build current version of plugin ... it is tricky and sometime works, but with more dependencies for another module can stop working ...

To be clear we should used previous version of plugin for site build.

**Comment by ajarmoniuk** [comment]
> > Looks like maven site requires the artifacts to be present in the local repo. So we need to do install -P run-its instead of verify in maven-verify.yml?
> 
> I see - we use under site build current version of plugin ... it is tricky and sometime works, but with more dependencies for another module can stop working ...
> 
> To be clear we should used previous version of plugin for site build

But that won't work - the previous version doesn't have modules 😏

Instead, why don't we do something like an extra Github Ci job before running site - Install with no tests, no enforcer, no chesktyle etc. Or compose that as an extra goal in the Site job?

**Comment by slawekjaranowski** [comment]
I changed to instal for first step build ... I'm waiting for build ...

**Comment by slawekjaranowski** [comment]
I'm want to go with this PR ... even more I can update site with snapshot version before release, so we can quickly resolve all site issues.

Next PR like enforcer rule can be put in separate module - What do you think?

**Comment by ajarmoniuk** [comment]
> I'm want to go with this PR ... even more I can update site with snapshot version before release, so we can quickly resolve all site issues.
> 
> Next PR like enforcer rule can be put in separate module - What do you think?

Definitely!

**Comment by ajarmoniuk** [comment]
Can we merge?

**Comment by slawekjaranowski** [comment]
So, merged ... next release will be very interesting 😄

**Comment by slawekjaranowski** [comment]
eeeh I forgot to squash 😠

**Pull request merged**
