### PR TITLE
added boolean forceNewVersion to update-property goal

### PR DESCRIPTION
**Pull request by oreporan**
we update our pom depedencies based on properties and need the abilityn to roll back to older versions automatically based on testing. Currently the update-property goal only updates to the latest versions (effectively ignoring the newVersion property if it isn't the latest)

The fix is a simple if/else on a new boolean property `-DforceNewVersion=true` 
If this is set to true (default false), then the code runs over all the versions of the depedency linked to this property, and as long as this version exists, it is set. If the version doesn't exist at all, this leaves the property unchanged (like the original code)

### CODE REVIEW

**Comment by oreporan** [comment]
possible dupliate of #119

**Comment by sregger** [comment]
@oreporan did this change get released? I'm looking to start using

> mvn versions:update-property

with

> -DnewVersion

and like you I'd need to support rollbacks.

**Comment by oreporan** [comment]
@sregger - I have no idea. It appears it was never merged..

**Comment by sregger** [comment]
Pity - thanks for the update @oreporan

**Comment by khmarbaise** [comment]
Hi, currently I'm working on a larger number of changes...at the moment I see that this PR has conflicts in it..furthermore I don't see tests for this new behaviour...It would also helpful having a squashed commit which contains the whole change in a single commit ...

**Comment by sregger** [comment]
@oreporan and @khmarbaise 

I was too quick to hop on this bandwagon. Turns out that -DnewVersion supports rollbacks. But it has bad error detection for arguments.

I was using the command like so

> mvn versions:update-property -DnewVersion=1.0.123 -Dproperty=my-property.version

which **always** upgrades to the latest. I did not notice this as 1.0.123 was my latest. But I did notice I could not downgrade once I'd set 1.0.123.

However this command is incorrect. The correct command is

> mvn versions:update-property -DnewVersion=[1.0.123] -Dproperty=my-property.version

You need to use the range when setting a newVersion. e.g. [1.0.123] versus 1.0.123

Now I'm able to rollback to old versions.

**Comment by sregger** [comment]
Further info

If the property name is specified incorrectly unexpected behavior is encountered.

e.g.

> -Dproperty=my-version instead of my.version

This causes no warning or error. But -DnewVersion is ignored and instead the **latest** version is set. 

> -Dproperty=my-version instead of my.version

In the above the dot (.) was replaced with a dash (-).

This caused no property matches and hence no changes.

It seems maven checks if any property is contained within the provided -DnewVersion

**Comment by khmarbaise** [comment]
The handling for downgrade a version to a previous version has been done with #98  
```
mvn versions:update-property -Dproperty=testng.version -DnewVersion=[5.6] -DallowDowngrade=true
```
this will allow downgrade of this property to version `5.6` ...
Apart from that if you don't see something in the log like:
```
[INFO] --- versions-maven-plugin:2.5-SNAPSHOT:update-property (default-cli) @ parent ---
[INFO] Major version changes allowed
[INFO] Updated ${testng.version} from 5.8 to 5.6
```
or
```
[INFO] --- versions-maven-plugin:2.5-SNAPSHOT:update-property (default-cli) @ module-a2 ---
[INFO] Major version changes allowed
[INFO] Property ${testng.version}: Leaving unchanged as 5.8
```
Than the given property was not found in the reactor. I have to admit it makes more sense to give a warning in such cases (will be a separate issue #171 ).

**Comment by sregger** [comment]
Another area where a warning would be nice is the following

    <properties>
        <my-property.version>1.0.122</my-property.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            
            <dependency>
                <groupId>my.group.id</groupId>
                <artifactId>artifact-A</artifactId>
                <version>${my-property.version}</version>
            </dependency>

            <dependency>
                <groupId>my.group.id</groupId>
                <artifactId>artifact-B</artifactId>
                <version>${my-property.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

> mvn versions:update-property -DnewVersion=1.0.123 -Dproperty=my-property.version

where artifact-A was published for release 1.0.123 but artifact-B was not. In this case the plugin correctly refuses to update the property version. i.e. As this would create an invalid dependency definition for artifact-B.

But it'd be nice for the plugin to print a warning about why the update did not occur. Instead of silently failing. Even if you enable debugging (-X) there is not enough information to tell why the update did not occur. i.e. The messages are the same as when setting an invalid version. This also makes it harder to track down which dependency is no longer published.

Ideally the plugin would print out which dependencies match the new version & which do not match. In general it'd be nice to know why the update did not occur. e.g.

> Property ${my-property.version}: No dependencies match the supplied version leaving unchanged as 1.0.122

> Property ${my-property.version}: Unable to find any repository holding dependencies matching the supplied version leaving unchanged as 1.0.122

> Property ${my-property.version}: Not all dependencies have an artifact matching the supplied version leaving unchanged as 1.0.122
> Matched dependencies: my-group-id:artifact-A, ....
> Unmatched dependencies: my-group-id:artifact-B, ....

**Comment by khmarbaise** [comment]
Can we make a new issue for that please...

**Comment by sregger** [comment]
Submitted https://github.com/mojohaus/versions-maven-plugin/issues/174

**Pull request closed without merging**
