### PR TITLE
Fixing #769

### PR DESCRIPTION
**Pull request by ajarmoniuk**
Obvious fix + unit tests.

Please add to the release if still possible.

### CODE REVIEW

**Comment by pzygielo** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

Note: "fixing" is not recognized as closing keyword and it does not link PR with issue.

**Comment by pzygielo** [comment]
- #769

**Comment by ajarmoniuk** [comment]
> https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
> 
> Note: "fixing" is not recognized as closing keyword and it does not link PR with issue.

Thanks

**Comment by slawekjaranowski** [comment]
> > https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
> > Note: "fixing" is not recognized as closing keyword and it does not link PR with issue.
> 

keywords can be also used in commit message - not necessary in commit subject 😄

**Comment by pzygielo** [comment]
> > > https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
> > > Note: "fixing" is not recognized as closing keyword and it does not link PR with issue.
> 
> keywords can be also used in commit message - not necessary in commit subject smile

As said here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Still - "fixing" is not a supported keyword.

**Comment by ajarmoniuk** [comment]
Pls merge 😏

**Pull request merged**
