### PR TITLE
[Bug 2.3] Classifier not correctly supported in lock-snaphots

### PR DESCRIPTION
**Pull request by ghilainm**
Fixed two bugs:
[Bug 2.3] Classifier not correctly supported in lock-snaphots + [Bug 2.3] Use-release not working

### CODE REVIEW

**Comment by glance-** [comment]
Looks to be a duplicate of #36

**Comment by ghilainm** [comment]
This is not I have fixed several stuff in this merge request. But there is one build not passing after the fix of a ticket don't know why must take a closer look

**Comment by glance-** [comment]
589ed82f7589bb81b35a69099cacceee6ec447cf is solving the same problem as I've done in #36 just in another way.

I would love to have one of those fixes merged.

**Comment by ghilainm** [comment]
Totally agree it has been ages since this merge request is created would be nice to have some news and comments on code changes!

**Comment by khmarbaise** [comment]
The fix for #36 has been merged into codebase...It would also be nice to separate pull request to fix only a single issue within a single pull request...furthermore currently these pull request have conflicts...

**Pull request closed without merging**
