### PR TITLE
#632 Fixed lower and upper bounds to keep milestones and rcs in the right majors.

### PR DESCRIPTION
**Pull request by sultan**
#632 Fix Bounds so lower and upper bounds keep milestones and rcs in the same majors when they are.

a quick before/after : 

image
image

### CODE REVIEW

**Comment by sultan** [comment]
basically this PR adds a "forceSnapshot" boolean to the increaseSegment method. this allows to create bounds that includes 4.0-snaphost 4.0-rc 4.0-m1 4.0-final in the same 4.0 major, for that we need that boolean to increase 3.0 into lower bound 4.0-snaphost included, and upper bound 5.0-snapshot excluded.

**Comment by ajarmoniuk** [comment]
Hi @sultan do you know if you still have much to do there? I'm working on a refactor which includes changes to UpdateScope (which may lead all the way to getting rid of it). There's a lot of old cruft which needs to be purged. Or maybe we could sync?

Here's the diff:

https://github.com/mojohaus/versions-maven-plugin/compare/master...ajarmoniuk:versions-maven-plugin:aj-5-segments-overhaul?diff=unified

**Comment by sultan** [comment]
All good. No more job needed on my side for this PR. 
I was hoping that these rc ordering things could be implemented in Maven git repo (their artifacts comparator)
If I ever succeed in persuading them to include rc ordering, maybe this job would have to be rethought. 

Agreeing on removing unused method, or a cleanup/refactoring.

**Comment by sultan** [comment]
I can’t have access to my computer this morning. If you can merge both today I’m fine. Though I can help a bit later

**Comment by ajarmoniuk** [comment]
Sure. If you still want to sync, let me know, we can merge our branches.

**Comment by sultan** [comment]
I'll try something in about 6 hours if it can help

**Comment by ajarmoniuk** [comment]
If you go and check in my class, UpdateScope is no more :laughing:

**Comment by sultan** [comment]
great job of factorization. i'll see if i can merge all of it in my PR tomorrow

**Comment by sultan** [comment]
rebased and ready.

**Comment by sultan** [comment]
if you need to merge #708 first, then there is room for me to improve my PR, it seems the forceSnaphsot will be always true after all. then i can simplify everything.

**Comment by slawekjaranowski** [comment]
@sultan #708 merged

**Comment by sultan** [comment]
can Mercury versions allow snapshot qualifier ?
do i need to strip snapshot qualifier before incrementing a NumericVersion ?

**Comment by sultan** [comment]
rebased but requires your attention on above questions before merging

**Comment by ajarmoniuk** [comment]
Looks like it did support -SNAPSHOT and similar qualifiers.

https://www.mail-archive.com/dev@maven.apache.org/msg77826.html

https://www.mail-archive.com/dev@maven.apache.org/msg76344.html

**Comment by sultan** [comment]
the PR currently generates bounds with a "-SNAPSHOT" qualifier, *always*, regardless of comparator (Maven, Mercury, NumericVersion). the current result is tested against all three Test classes which I modified to expect always the snapshot qualifier. if these Tests classes are okay for the reviewers, then the PR can be merged.
my tests on Maven poms are okay.

image

**Comment by slawekjaranowski** [comment]
In the latest picture we have:
```
4.0.0-RC1 Next Major
4.0.0-RC2
```

Should 4.0.0-RC2 will be Next Major instead of 4.0.0-RC1?

**Comment by sultan** [comment]
Not sure about differentiating RC1 vs RC2. the question of differentiating RC1 vs M1 however is another issue that may be adressed in another PR. the problem is caused by dashes and dots not treated the same way. 

The result could better be M1 Next Major followed by RC1 RC2. 

this problem was already there before the PR. I know the involved class but I did not investigate the solution. 

The improvement done in this PR is having M1 RC1 RC2 and Realease labelled in the same major. 

I'm open to improvement if you can provide a textual expected rendering.

**Comment by sultan** [comment]
as a result of fixing #632, it appears we could maybe get rid of the class MajorMinorIncrementalFilter which states that its very existence is filtering milestones and RC from the result of the calls, which are now already filtered out by my PR.

thanks @slawekjaranowski for the merge with the master branch.

i did it on my own branch to avoid losing your push next time.

maybe better for us that i remove MajorMinorIncrementalFilter in another PR ?

**Pull request merged**
