### PR TITLE
#717: Changing the property prefix to mojohaus.versions

### PR DESCRIPTION
**Pull request by ajarmoniuk**

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
I'm not sure if we should brake compatibility for old properties in simply way.

We rename two old properties:
 - maven.version.rules.serverId
 - maven.version.rules
 
Probably such properties not widely used, but in this case I would prefer one PR for one property to show such change in releases notes.

**Comment by ajarmoniuk** [comment]
Yeah, that was my concern as well... And there's no easy way of providing an alias to a property, besides creating a second parameter.

Should we just leave these two parameters as they are and just rename the third one?

**Comment by slawekjaranowski** [comment]
I don't expect a big impacts on users - I think that when we show it in release notes will be acceptable - parameter name for configuration are not changed

**Comment by ajarmoniuk** [comment]
I've just noticed this:

```
@Parameter( property = "versions.skip" )
```

Should we go for the `versions.` prefix then?

**Comment by pzygielo** [comment]
> Should we go for the `versions.` prefix then?

:+1:

**Comment by pzygielo** [comment]
Just linking to
- #717

**Pull request closed without merging**
