### PR TITLE
Fixing #315: Guarding against newVersion or property being empty if the properties file is not provided

### PR DESCRIPTION
**Pull request by ajarmoniuk**
Simple fix + unit test

### CODE REVIEW

**Comment by Koziol1991** [comment]
This is a problematic fix, as now we can't unset property, which is already in pom.xml

**Comment by slawekjaranowski** [comment]
@Koziol-ku thanks for info. 

Please create new issue with example project/pom which can be used to reproduce.

**Comment by ajarmoniuk** [comment]
@Koziol-ku could you please elaborate and, if possible, create a ticket with reproduction steps and pom? The idea was to protect against an NPE which occurred if either `version` or `property` was _empty_.

**Comment by spyrolabs** [comment]
Using `mvn versions:set-property -Dproperty=changelist -DnewVersion=` where we have `<changelist>-SNAPSHOT</changelist>`  would have become `<changelist></changelist>` with version 2.11.0. With version 2.12.0, we have the error explained by @Koziol-ku

**Comment by ajarmoniuk** [comment]
Thanks, I'll fix that.

**Comment by ajarmoniuk** [comment]
Created a PR restoring that.

**Pull request merged**
