### PR TITLE
versions:set -DremoveSnapshot=true

### PR DESCRIPTION
**Pull request by designhaiku**
Hi,

   I added a new property to the set command.  The property "removeSnapshot=<true|false>" allows for computing the newVersion property off of the existing version and removing the "-SNAPSHOT".  
I believe others would benefit from this.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Could you please squash your commits to have single commit which contains the changes.

**Comment by bpindelski** [comment]
Hi @khmarbaise 
This PR has now been dormant for 3 months, but the feature is really useful (at least for me). Is there antything I could do to make this PR mergeable (besides conflict resolution)?

**Comment by tchemit** [comment]
Hi @bpindelski , I will try to up this one this week ;).

**Comment by tchemit** [comment]
@bpindelski Did you squash the PR as asked by @khmarbaise ?

**Comment by bpindelski** [comment]
Hi @tchemit 
Thanks for the fast reply!
I'm not the original author of the PR. @designhaiku hasn't been active on GitHub lately. I'll see what can be done regarding squashing.

**Comment by khmarbaise** [comment]
Fix done in #91

**Pull request closed without merging**
