### PR TITLE
Merge in origin/master and fix compilation errors and unit tests

### PR DESCRIPTION
**Pull request by epabst**

### CODE REVIEW

**Comment by epabst** [comment]
The ITs fail, but at least it compiles and passes unit tests.  I'm trying to figure out the ITs now.

**Comment by epabst** [comment]
This passes for java 8.  I'm not sure how to interpret the build failures for Java 6 and 7.

**Comment by khmarbaise** [comment]
JDK 6 and 7 seemed to be a problem with .travis file...will take a look at it...

**Comment by epabst** [comment]
I merged in the latest from origin/master in case that helped.  It should eliminate JDK 6 at least.

**Comment by khmarbaise** [comment]
Can you please squash your commits...usually you should rebase instead of merging...

**Comment by epabst** [comment]
I also prefer rebasing, but this is on top of a branch that you created.  It would result in a force push or deleting your original branch.  Would you like me to create such a branch?

**Comment by khmarbaise** [comment]
Just make a force push...I'm informed so it's not a problem..

**Comment by epabst** [comment]
Replaced by #290

**Pull request closed without merging**
