### PR TITLE
Fixing #755: Segment names containing Optional were used as tag names in XML reports

### PR DESCRIPTION
**Pull request by ajarmoniuk**

### CODE REVIEW

**Comment by ajarmoniuk** [comment]
@slawekjaranowski @slachiewicz please review

**Comment by ajarmoniuk** [comment]
Alternative: https://github.com/mojohaus/versions-maven-plugin/pull/757

**Comment by slawekjaranowski** [comment]
I'm for modelo - we can create XSD schema and documentation automatically.

**Comment by slawekjaranowski** [comment]
I suppose that this one can be closed, when we choose moelo alternative: #757

**Comment by ajarmoniuk** [comment]
> I suppose that this one can be closed, when we choose moelo alternative: #757

of course.

I'm currently working on this regression saw by @sultan -- #760.

The root cause is the fact that I was only adding "-snapshot" in `incrementSegment` to snapshot versions. This was initially done (before this "infinity calculus") because "-snapshot" is treated as the lowest possible version, lower than the release, which acts as a pseudo "minus infinity".

Well, I could either do that or introduce a real "minus infinity".

**Comment by ajarmoniuk** [comment]
The "-segment" approach seems to be fixing the issue; trying the more ambitious approach ;)

**Pull request closed without merging**
