### PR TITLE
Clarification in README - maintained versions, issues and PR creation

### PR DESCRIPTION
**Pull request by slawekjaranowski**
According to clarification we can only test with the latest Maven on GitHub it will save time for executing

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
What do you think @slachiewicz, @stefanseifert, @ajarmoniuk, @sultan

**Comment by sultan** [comment]
i would say let's move forward and be clear on the minimal maven version needed to run the plugin.
any chance we move to maven 4 when available?

**Comment by ajarmoniuk** [comment]
I think we need to check the minimal version supported as well as a current version - which can be the latest release or some other one we choose. But without testing with the minimal version we can not be sure if we really support it.

**Comment by slachiewicz** [comment]
Maybe we should explicitly say that we recommend Maven 3.8.6 (plus link) and add note to verify if issue can be reproduced also with latest version of Maven

**Comment by slawekjaranowski** [comment]
> i would say let's move forward and be clear on the minimal maven version needed to run the plugin. any chance we move to maven 4 when available?

Maven 4 API is not compatible backward to Maven 3, so it is for discussion later.

**Comment by slawekjaranowski** [comment]
> I think we need to check the minimal version supported as well as a current version - which can be the latest release or some other one we choose. But without testing with the minimal version we can not be sure if we really support it.

I know that when we will testing only with latest versions of Maven some of issue can be detected. 

But only checking minimum version doesn't make us sure that will be work with all other older versions like 3.3.x, 3.5.x, 3.6.x

When someone detect an issue with Maven 3.5.x - I want not spend time for resolving it.

**Comment by slawekjaranowski** [comment]
> Maybe we should explicitly say that we recommend Maven 3.8.6 (plus link) and add note to verify if issue can be reproduced also with latest version of Maven

Exactly it is my idea and my proposition in change.

**Pull request merged**
