### PR TITLE
#762 Fix Plugin Report and Success/Warning icons, counts

### LINKED ISSUE #762: Plugin Report table and icons broken
image

Firstly, Thanks for the awesome job of refactoring, the model and cache is a bliss,

the icons could also be green if count == 0 and orange if not.

Working on it, almost finished.

### PR DESCRIPTION
**Pull request by sultan**
Fixed #762

image

### CODE REVIEW

**Comment by sultan** [comment]
i can rebase this branch to ease review or leave it be. @slawekjaranowski ?

**Comment by slawekjaranowski** [comment]
@sultan I already rebased with the latest master and squash to final commit yesterday

**Comment by sultan** [comment]
Here is the proposed result with the verbosity options to false

image

**Comment by sultan** [comment]
just to be sure we are on the same page,
* this pr includes changes in 3 files that are not yet merged into main.
* is ready/ can be marged

**Comment by slawekjaranowski** [comment]
> just to be sure we are on the same page,
> 
> * this pr includes changes in 3 files that are not yet merged into main.

which files are not merged? ... I don't see

> * is ready/ can be marged

**Comment by sultan** [comment]
src/main/java/org/codehaus/mojo/versions/reporting/
* AbstractVersionsReportRenderer.java
* PluginUpdatesReportRenderer.java
* VersionsReportRendererBase.java

**Pull request merged**
