### PR TITLE
Removal of not needed calls to toString() in the code base

### LINKED ISSUE #466: Remove not needed calls to toString()
I would like to help to improve the code base of the Versions plugin and therefore I would like to suggest to remove all not needed calls to toString() in the code base. 

Even if this is a small change and it might not be an issue, I think it will help to improve the readability and the quality of the code.

### PR DESCRIPTION
**Pull request by obfischer**
Fixes #466 
 o Removed not needed calls to toString() to improve the code base

### CODE REVIEW

**Review by bmarwell — APPROVED** [review]

**Comment by obfischer** [comment]
Hi @bmarwell,

thank you for your review. How can perform the merge of this pull request?

**Comment by bmarwell** [comment]
Hi @obfischer can you undo the second  commit please? The merge commit is not needed.

**Review by bmarwell — CHANGES_REQUESTED** [review]
Please undo the merge commit. You probably meant to rebase it instead.

**Comment by obfischer** [comment]
Rebased on `master`.

**Review by bmarwell — APPROVED** [review]

**Comment by obfischer** [comment]
Hi @bmarwell, who can merge it? I don't have the permissions according to the UI.

**Pull request merged**
