### PR TITLE
Fixes #426 restore default behavior on setting versions in all modules of the local aggregation root that was present before the fix for #82

### LINKED ISSUE #426: 2.8.x: Unable to set project version when parent POM is in a project subdirectory
The changes for 2.8.1 break the `versions:set` goal for any project that has a parent POM (e.g. a Bill of Materials POM) in a subdirectory.

Project directory structure:

```
+- pom.xml
+- product-bom
|   \- pom.xml
+- product-module1
|   \- pom.xml
|   \- src
|       \- ...
+- product-module2
|   \- pom.xml
|   +- src
|       \- ...
...
```

Extract from `pom.xml`:

```xml
  <parent>
    <groupId>org.test.product</groupId>
    <artifactId>product-bom</artifactId>
    <relativePath>product-bom/pom.xml</relativePath>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <groupId>org.test.product</groupId>
  <artifactId>test-product</artifactId>
  <packaging>pom</packaging>
```

Extract from `product-bom/pom.xml`:

```xml
  <groupId>org.test.product</groupId>
  <artifactId>product-bom</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
```

Running `mvn versions:set -DnewVersion=2.0.0-SNAPSHOT --file product-bom/pom.xml` succeeds, but only updates the project version in `product-bom/pom.xml` - this breaks the project structure, as the test-product POM and product-bom POM version numbers no longer match.

Running `mvn versions:set -DnewVersion=2.0.0-SNAPSHOT` fails with the following message:
```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.8.1:set (default-cli) on project test-product: Project version is inherited from parent. -> [Help 1]
```

Please could you revert this breaking change?

### PR DESCRIPTION
**Pull request by stefanseifert**
introduce a new flag processFromLocalAggregationRoot that enables the new (and probably more correct) behavior by setting it it false
ensure old and new behavior are covered by integration tests

Fixes #426

### CODE REVIEW

**Comment by robincsmith** [comment]
Any news on this? As we're starting to approach the anniversary of this PR :-)

**Comment by bmarwell** [comment]
Hey @robincsmith  thanks for your PR! I will review it soon. Sorry for the delay! ;-)

**Comment by bmarwell** [comment]
Did a quick check with such a layout:

```
pom.xml
project-parent/pom.xml
```

Contents of `/pom.xml`:

```xml
   <parent>
     <groupId>invalid.company.project</groupId>
     <artifactId>project-parent</artifactId>
     <version>2.9.0-SNAPSHOT</version>
     <relativePath>project-parent/pom.xml</relativePath>
   </parent>
```

Executed:
```
mvn -X org.codehaus.mojo:versions-maven-plugin:2.9-SNAPSHOT:set -DnewVersion=2.9.0-SNAPSHOT -DgenerateBackupPoms=false
[...]
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.9-SNAPSHOT:set (default-cli) on project myproject: Project version is inherited from parent. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.9-SNAPSHOT:set (default-cli) on project myproject: Project version is inherited from parent.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Project version is inherited from parent.
    at org.codehaus.mojo.versions.SetMojo.execute (SetMojo.java:225)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by robincsmith** [comment]
Indeed. That matches the behaviour for version 2.7 and earlier:

```
$ mvn -X org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=2.9.0-SNAPSHOT -DgenerateBackupPoms=false
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:set (default-cli) on project test-project: Project version is inherited from parent. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:set (default-cli) on project test-project: Project version is inherited from parent.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Project version is inherited from parent.
    at org.codehaus.mojo.versions.SetMojo.execute (SetMojo.java:215)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :test-project
```

The Maven invocation needs to include the link to the parent POM (as it did for versions <2.7) - in your case, `-f project-parent/pom.xml`:
```
mvn -X org.codehaus.mojo:versions-maven-plugin:2.9-SNAPSHOT:set -DnewVersion=2.9.0-SNAPSHOT -DgenerateBackupPoms=false -f project-parent/pom.xml
```

**Comment by bmarwell** [comment]
But that will not change any other pom files. E.g. the `/pom.xml` containing the version of the parent pom.

**Comment by robincsmith** [comment]
Ah, in that case (from having a quick look at the RP), I think you may need to set `-DprocessFromLocalAggregationRoot=false`.

I'm not sure, as it's @stefanseifert 's PR. I'll try building their code.

**Comment by stefanseifert** [comment]
the start of this story was bug #82, for which i provided the PR #400 which was merged and released.
however, after that lots of people complained that from their pov the previous behavior was not a bug but works as intended, summed up by @robincsmith  in #426.

this PR restored the previous behavior to work exactly as it was for years in the previous versions of the plugin - but still allows to switch on the new behavior as described in #82. the new behavior only gets active when plugin property `processFromLocalAggregationRoot` is set to true (default is false).

ITs are included to cover both old and new behavior.

**Comment by robincsmith** [comment]
@stefanseifert agreed - thanks for confirming.

@bmarwell  I've just built the PR code, and the following should work for you, running in the project root directory:
```
mvn -X org.codehaus.mojo:versions-maven-plugin:2.9-SNAPSHOT:set -DnewVersion=1.2.3-SNAPSHOT -DgenerateBackupPoms=false -f project-parent/pom.xml
```
(i.e. no need to set any other flags, such as `processFromLocalAggregationRoot`)

**Comment by robincsmith** [comment]
The only thing I can think is that you might have another snapshot version of the plugin installed? As the behaviour looks unchanged for you.

My plugin installation steps were just to checkout the PR code and run `mvn clean install`

**Comment by bmarwell** [comment]
Did the same, and as I use -X I can see the new property. Hmmm.

But if I use the file parameter and point to the parent not containing any modules, how would Maven know about the root? 🤷🏻‍♂️

I have another specialty in my project.
I manage module versions in my parent pom. Maybe I should not do this and just repeat the version everywhere.

**Comment by bmarwell** [comment]
As soon as I started repeating the versions in all other modules again, it worked again.

**Comment by gunnarmorling** [comment]
Running into this in ModiTect as well; as a work-around, we've downgraded that invocation to 2.7 for the time being: https://github.com/moditect/moditect/blob/master/.github/workflows/trigger.yml#L87.

**Comment by stefanseifert** [comment]
if there are no objections i will merge this PR next week as lot of people seem to depend on the old behavior.
the new behavior is still available by setting `processFromLocalAggregationRoot=false` in the plugin config.

**Comment by stefanseifert** [comment]
merged to master with https://github.com/mojohaus/versions-maven-plugin/commit/279d90a805fbb1d736bd6464420bc0636f410b0f

**Pull request merged**
